### ISSUE TITLE
Endless loop with RSpec

### ISSUE THREAD

**Issue by aradunovic** [amitree/delayed_job_recurring#11]
I'm using [delayed_job_active_record](https://github.com/collectiveidea/delayed_job_active_record) and delayed_job_recurring. Everything works great in development and production. However, in test environment I'm getting `Stack level too deep` exception when testing recurring jobs.

I configured Delayed job to work synchronously when running specs:

``` ruby
Delayed::Worker.delay_jobs = false
```

My current (not so great) workaround is to include RecurringJob only outside of test env:

``` ruby
class MyRecurringJob
    unless Rails.env.test?
        include Delayed::RecurringJob
        run_every 5.minutes
    end

# ...

end
```

I'm using:
- rails 4.2.0
- rspec 3.1.7
- database_cleaner 1.4.1
- delayed_job 4.1.1
- delayed_job_active_record 4.1.0
- delayed_job_recurring 0.3.5

**Comment by ericchapman** [comment]
I ended up surrounding my config file as follows
```ruby
if Rails.env.production?
  MyJob.schedule!
end
```

and then just calling my scheduled jobs manually in Rspec
``` ruby
it 'performs the job' do
  MyJob.perform
end
```

This allowed me to test the work that the job was doing by bypassing the scheduled aspect of it.
