### ISSUE TITLE
Job is not recurring

### ISSUE THREAD

**Issue by bsutherland** [amitree/delayed_job_recurring#14]
I've defined a job along the lines of:

``` ruby
class HealthCheckTask
  include Delayed::RecurringJob

  run_every 5.minutes
  ...
```

And schedule it with:

`HealthCheckTask.schedule!`

But it only executes once. Any suggestions as to why?

**Comment by jonaizen** [comment]
Try inheriting instead of including.

**Comment by bsutherland** [comment]
Thanks Jonathon, I'll give it a try. Is this dependent on ActiveJob version?

**Comment by jonaizen** [comment]
Now that I look at our code, I see we do it like this:

```
module Recurring
  class SomeClass
    include Delayed::RecurringJob
```

So including is the right way to go. I'm not sure why it is only executing once for you. After it executes, do you see the newly created Delayed::Job in your database or not?

**Comment by bsutherland** [comment]
When I schedule it the first time I see it, but after it executes one it
doesn't seem to reschedule itself (doesn't appear in the table again).

**Comment by derrelldurrett** [comment]
I'm possibly experiencing this issue.

As an update to the information above, If I execute `rails restart` it does not update the schedule of the jobs.

**Comment by afn** [comment]
Can you try with the latest version of the gem? (0.3.6)

If you're still having issues, what version of delayed_job and delayed_job_active_record are you using?

**Comment by derrelldurrett** [comment]
After a lot of work in the meantime (unsurprising, given the amount of time passed), I think I have a different issue.

FWIW, I'm currently using 0.3.6.

**Comment by rdemuth** [comment]
I'm having exactly this issue.  i have a class like the following:

```
class `NightlyBatchJobs`
    include Delayed::RecurringJob
    run_every 1.day
    run_at '03:30pm'
    timezone 'US/Pacific'
    queue 'nightly'
    def perform
...
    end
```

I have a rake task (as suggested) that I run at deployment time to schedule the jobs.
A record gets put in the delayed_jobs table, and the job executes once.  But afterwards, there is no longer a record in the table and the job does not execute again.  I'm using version 0.3.7.  I'm a bit of noob . . .

**Comment by afn** [comment]
Let me see if I can reproduce this issue. Can you share your entire NightlyBatchJobs class? (Or better yet, replace the body of the `perform` method with something simple, like `puts "hello"`, and confirm that it's still failing to reschedule the job)

**Comment by rdemuth** [comment]
Thanks for responding. 
I had already commented out nearly all the functionality in the class.  It looked like this:

class NightlyBatchJobs include Delayed::RecurringJob
run_every 1.day
run_at '03:30pm'
timezone 'US/Pacific'
queue 'nightly'
def perform
  d = ApplicationHelper.get_market_date(Date.today)
  return if d != Date.today()

#Commented out stuff
end

def success(job)
  logger.info 'Successfully completed nightly job'
end

def error(job, exception)
  logger.info "Nightly job error:  #{exception}"
end

def failure(job)
  logger.info 'Nightly job failure'
end
endThe success method ran the one time.
 

    On Monday, October 30, 2017, 12:50:45 PM PDT, Tony Novak <notifications@github.com> wrote:  
 
 
Let me see if I can reproduce this issue. Can you share your entire NightlyBatchJobs class? (Or better yet, replace the body of the perform method with something simple, like puts "hello", and confirm that it's still failing to reschedule the job)

**Comment by afn** [comment]
Ah, I see what's happening. `Delayed::RecurringJob` reschedules itself in the [`success` and `failure` methods](https://github.com/amitree/delayed_job_recurring/blob/master/lib/delayed/recurring_job.rb#L16-L22), so overriding these methods prevents rescheduling.

There may be a better way to handle this, but for now, if you define `success` or `failure`, you'll need to call `super`.

**Comment by rdemuth** [comment]
Well, that at least makes sense.  
 

    On Tuesday, October 31, 2017, 5:05:20 AM PDT, Tony Novak <notifications@github.com> wrote:  
 
 
Ah, I see what's happening. Delayed::RecurringJob reschedules itself in the success and failure methods, so overriding these methods prevents rescheduling.

There may be a better way to handle this, but for now, if you define success or failure, you'll need to call super.

**Comment by rdemuth** [comment]
It turns out that 'success' is where the recurring job gets rescheduled, so if you define a success (or failure) method for your recurring job, you will need to call super.  

Thanks to Tony Novak for this insight.
